name: CI

on:
  push:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t mtahatavaci/hello-world-pflask:${{ github.run_number }} .
          docker tag mtahatavaci/hello-world-pflask:${{ github.run_number }} mtahatavaci/hello-world-pflask:latest

      - name: Push Docker image
        run: |
          docker push mtahatavaci/hello-world-pflask:${{ github.run_number }}
          docker push mtahatavaci/hello-world-pflask:latest
